// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const configuredUrl = import.meta.env.VITE_SUPABASE_URL?.trim();
const configuredKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim();

/**
 * True when production Supabase frontend credentials were supplied at build time.
 * The portfolio can still render without them; auth/subscription actions will fail
 * gracefully until the original project's public credentials are restored.
 */
export const isSupabaseConfigured = Boolean(configuredUrl && configuredKey);

// Supabase's client constructor requires non-empty values. Use a deliberately
// non-production fallback endpoint/key only to keep public portfolio routes alive
// when the original Supabase project is unavailable to the deployment pipeline.
const SUPABASE_URL = configuredUrl || 'https://unconfigured.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = configuredKey || 'unconfigured-public-key';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
